common:
  namespace: elk-cluster-ns
  secretName: azure-registry
  registry: ${REGISTRY_URL}

elasticsearch:
  image:
    tag: ${TAG}
  client:
    replicas: 2
  master:
    replicas: 3
  data:
    replicas: 2
    storageAccount: ${STORAGE_ACCOUNT}
    location: ${STORAGE_LOCATION}
    storageSku: ${STORAGE_SKU}

kibana:
  image:
    tag: ${TAG}
  replicaCount: 1

logstash:
  image:
    tag: ${TAG}
  replicaCount: 1
