common:
  namespace: elk-cluster-ns
  secretName: azure-registry
  registry: <registry_name>.azurecr.io

elasticsearch:
  image:
    tag: 1.0.0
  client:
    replicas: 2
  master:
    replicas: 3
  data:
    replicas: 2
    storageAccount: azdisksa
    location: westus

kibana:
  image:
    tag: 1.0.0
  replicaCount: 1

logstash:
  image:
    tag: 1.0.0
  replicaCount: 1
